name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: ./mvnw clean package -DskipTests -q

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/ec2_key.pem
          chmod 400 /tmp/ec2_key.pem
          scp -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem \
            target/lending-platform-0.0.1-SNAPSHOT.jar \
            ubuntu@13.206.81.60:/home/ubuntu/app/lending-platform.jar
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem \
            ubuntu@13.206.81.60 \
            "sudo systemctl restart finpulse && sleep 20 && sudo systemctl is-active finpulse"
          rm -f /tmp/ec2_key.pem
